# this workflow will run on all pushes.
on:
  push:

name: "push"
jobs:
  test-default:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      - 
        uses: actions/setup-node@v4
      -
        name: Serve Files
        uses: ./
        with:
          directory: ${{ github.workspace }}/.github
          port: 9090
          no-cache: true
          content-types: |
            {
              "md": "text/markdown"
            }
      -
        run: node .github/test-default.js

  test-index-files:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        uses: actions/setup-node@v4
      -
        name: Serve Files
        uses: ./
        with:
          directory: ${{ github.workspace }}/.github
          port: 9090
          no-cache: true
          index-files: |
            ["PULL_REQUEST_TEMPLATE.md"]
      -
        run: node .github/test-index-files.js

  test-custom-404:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        uses: actions/setup-node@v4
      -
        name: Serve Files
        uses: ./
        with:
          directory: ${{ github.workspace }}/.github
          port: 9090
          no-cache: true
          custom404Page: "PULL_REQUEST_TEMPLATE.md"
      -
        run: node .github/test-custom-404.js

  test-default-404:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        uses: actions/setup-node@v4
      -
        name: Serve Files
        uses: ./
        with:
          directory: ${{ github.workspace }}/.github
          port: 9090
          no-cache: true
      -
        run: node .github/test-default-404.js        

  test-allowed-methods:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        uses: actions/setup-node@v4
      -
        name: Serve Files
        uses: ./
        with:
          directory: ${{ github.workspace }}/.github
          port: 9090
          no-cache: true
          allowed-methods: |
            ["POST"]
      -
        run: node .github/test-allowed-methods.js
  test-logging:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        uses: actions/setup-node@v4
      -
        name: Serve Files
        uses: ./
        with:
          directory: ${{ github.workspace }}/.github
          port: 9090
          no-cache: true
          allowed-methods: |
            ["GET", "POST"]
          log: log.txt
          logTime: false
      -
        run: node .github/test-logging.js


  # draft your next release notes as pull requests are merged into "master"
  # the configuration is at /.github/release-drafter.yml.
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        if: github.ref_name == github.event.repository.default_branch
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
